### ISSUE TITLE
Alts to BTC price decimal spaces

### ISSUE THREAD

**Issue by tomislavp** [sblaurock/crypticker#2]
Hi Steve,
I just stumbled upon crypticker, nice && simple, that's how is should be.

There is a problem with a price display from ALTS to BTC, it is only four decimal spaces after Zero. That's not enough for 'smaller' ALTS like XRP or GNT etc.

Could not find the way how to change it?

Attached are screenshots

Cheers,
T

![pkg_json](https://user-images.githubusercontent.com/308551/34361656-598aee06-ea6c-11e7-925c-2a9d3dd096e5.png)
![ticker](https://user-images.githubusercontent.com/308551/34361657-59aad504-ea6c-11e7-9872-470527a77444.png)

**Comment by sblaurock** [comment]
Hey @tomislavp - thanks for reaching out! This is a great find and I'd be happy to have a look. I will keep you updated with any progress.

**Comment by sblaurock** [comment]
Apologies for the delay in getting this fixed. With version 1.2.6 this should no longer be a problem. Thanks so much for bringing this to my attention - let me know if you have any further feedback and I'd be happy to have a look!
