### ISSUE TITLE
Data retrieval error

### ISSUE THREAD

**Issue by billzhong** [sblaurock/crypticker#3]
Hi,

I run:
```
$ crypticker
⚠ Data retrieval error / Last updated a few seconds ago

```

My system is:

```
$ node -v
v8.11.1
```

```
$ npm -v
6.4.1
```

```
$ uname -a
Linux raspberrypi 4.14.70-v7+ #1144 SMP Tue Sep 18 17:34:46 BST 2018 armv7l GNU/Linux
```

Any help? Thanks.

**Comment by sblaurock** [comment]
Hey @billzhong thanks for reaching out and sorry for the delay. It sounds like you're having a network issue connecting the endpoint used to retrieve price information. Are you able to load https://api.cryptowat.ch/exchanges from the machine with the issue?

**Comment by billzhong** [comment]
Hi @sblaurock I am able to load the URL from my local. Sorry I was busy recently. I will take a look later. Thanks.

**Comment by billzhong** [comment]
Hey @sblaurock I tried again today from different local network. It is working. Thanks.

**Comment by sblaurock** [comment]
Awesome! Thanks for raising this and I'm glad things are running smoothly again.
